const MAP_CAN_MOVE = 1;
const MAP_CAN_NOT_MOVE1 = 2;
const MAP_ITEM = 3;



class Map{
    constructor() {
        this.map = [
            [MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1],
            [MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1],
            [MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1],
            [MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1],
            [MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1],
            [MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1],
            [MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1,MAP_CAN_NOT_MOVE1]
        ]
    }

    getState(x,y){
        return this.map[y][x];
    }

    setState(x, y, newState){
        this.map[y][x] = newState;
    }
}
