stages:
  - deploy

develop-deploy:
  type: deploy
  script:
    - mkdir -p "${PROJECT_DIR}/develop"
    - cp -r index.html images js music javascript_compressed.js stylesheet.css "${PROJECT_DIR}/develop/"
  only:
    - develop

master-deploy:
  type: deploy
  script:
    - mkdir -p "${PROJECT_DIR}/master"
    - cp -r index.html images js music javascript_compressed.js stylesheet.css "${PROJECT_DIR}/master/"
  only:
    - master

merge-request-deploy:
  type: deploy
  script:
    - mkdir -p "${PROJECT_DIR}/${CI_MERGE_REQUEST_IID}"
    - cp -r index.html images js music javascript_compressed.js stylesheet.css  "${PROJECT_DIR}/${CI_MERGE_REQUEST_IID}/"
    - deploy_url="${URL}/${CI_MERGE_REQUEST_IID}"
    - "curl -H \"Content-Type: application/json\" -d '{\"username\": \"GitLabRunner\", \"content\": \"'\"${deploy_url}\"'\"}' \"${WEBHOOK}\""
  only:
    - merge_requests
