stages:
  - deploy

develop-deploy:
  type: deploy
  script:
    - cp -r * $PROJECT_DIR_DEVELOP
    - cd $PROJECT_DIR_DEVELOP
    - docker-compose -f docker-compose-develop.yml down
    - docker-compose -f docker-compose-develop.yml build
    - docker-compose -f docker-compose-develop.yml up -d
  only:
    - develop

master-deploy:
  type: deploy
  script:
    - cp -r * $PROJECT_DIR_MASTER
    - cd $PROJECT_DIR_MASTER
    - docker-compose -f docker-compose-master.yml down
    - docker-compose -f docker-compose-master.yml build
    - docker-compose -f docker-compose-master.yml up -d
  only:
    - master

merge-request-deploy:
  type: deploy
  script:
    - echo "${PROJECT_DIR}/${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA}"
    - mkdir -p "${PROJECT_DIR}/${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA}"
    - cp -r * "${PROJECT_DIR}/${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA}/"
  only:
    - merge_requests