stages:
  - deploy

develop-deploy:
  type: deploy
  script:
    - echo "${PROJECT_DIR}/develop"
    - mkdir -p "${PROJECT_DIR}/develop"
    - cp -r * "${PROJECT_DIR}/develop/"
  only:
    - develop

master-deploy:
  type: deploy
  script:
    - echo "${PROJECT_DIR}/master"
    - mkdir -p "${PROJECT_DIR}/master"
    - cp -r * "${PROJECT_DIR}/master/"
  only:
    - master

merge-request-deploy:
  type: deploy
  script:
    - echo "${PROJECT_DIR}/${CI_MERGE_REQUEST_IID}"
    - mkdir -p "${PROJECT_DIR}/${CI_MERGE_REQUEST_IID}"
    - cp -r * "${PROJECT_DIR}/${CI_MERGE_REQUEST_IID}/"
    - deploy_url="${URL}/${CI_MERGE_REQUEST_IID}"
    - curl -H "Content-Type: application/json" -d '{"username": "GitLabRunner", "content": "'"${deploy_url}"'"}' "${WEBHOOK}"
  only:
    - merge_requests